# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 02:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='empleado',
            field=models.ManyToManyField(related_name='reserva_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reserva',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_site.Sala_reuniones'),
        ),
    ]
